# Generated by Django 5.0 on 2024-02-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('PhoneNo', models.IntegerField()),
                ('Birthday', models.DateField()),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
    ]
