# Generated by Django 5.0 on 2024-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highschool', models.CharField(max_length=50)),
                ('highschool_date', models.IntegerField()),
                ('highschool_experiences', models.TextField(default='Experience in highschool')),
                ('interschool', models.CharField(max_length=50)),
                ('interschool_date', models.IntegerField()),
                ('interschool_experiences', models.TextField(default='Experience in Interschool')),
                ('Graduation', models.CharField(max_length=50)),
                ('Graduation_date', models.IntegerField()),
                ('Graduation_experiences', models.TextField(default='Experience in Graduation')),
            ],
        ),
    ]
