# Generated by Django 5.0 on 2024-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='highschool_date',
            new_name='TimeLapse',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Graduation',
            new_name='schooling',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='Graduation_date',
            new_name='schooling_date',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='highschool_experiences',
            new_name='schooling_experiences',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='Graduation_experiences',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='highschool',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interschool',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interschool_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interschool_experiences',
        ),
        migrations.AddField(
            model_name='resume',
            name='Experience',
            field=models.TextField(default='Experience in workingcompany'),
        ),
        migrations.AddField(
            model_name='resume',
            name='post',
            field=models.CharField(default='Experience in Graduation', max_length=50),
        ),
    ]
